Endpoints controll access
projetoKhali/api5back pull request #75
Opened 2024-11-23 20:23 UTC by Incivius

Criei os enpoints de controle de acesso:

`GRUPO DE ACESSO`:

Listar os grupos de acesso:

`GET/` http://localhost:8080/api/v1/groupAccess/List

Exemplo do retorno:

```
[
    {
        "id": 1,
        "name": "ADM",
        "departments": [
            {
                "id": 1,
                "title": "Marketing"
            },
            {
                "id": 2,
                "title": "Rh"
            },
            {
                "id": 3,
                "title": "CX"
            },
            {
                "id": 4,
                "title": "CEO"
            },
            {
                "id": 5,
                "title": "Comer"
            }
        ]
    },
    {
        "id": 2,
        "name": "RH",
        "departments": [
            {
                "id": 1,
                "title": "Marketing"
            },
            {
                "id": 2,
                "title": "Rh"
            }
        ]
    },
    {
        "id": 3,
        "name": "Marketing",
        "departments": [
            {
                "id": 1,
                "title": "Marketing"
            }
        ]
    },
    {
        "id": 4,
        "name": "Tech",
        "departments": [
            {
                "id": 1,
                "title": "Marketing"
            },
            {
                "id": 2,
                "title": "Rh"
            },
            {
                "id": 3,
                "title": "CX"
            },
            {
                "id": 4,
                "title": "CEO"
            },
            {
                "id": 5,
                "title": "Comer"
            }
        ]
    }
]
```

**********************************

Parar criar novos grupos de acesso:
 `POST/` http://localhost:8080/api/v1/groupAccess/List

Body => 

```
{
  "name": "Nome do grupo",
  "departments": [1, 2, 3]
}
```

retorno:

```
{
    "id": 5,
    "name": "Nome do grupo"
}
```
-------------------------------------

`DEPARTAMENTO`

Listar os departamentos:

`GET/` http://localhost:8080/api/v1/suggestions/department

retorno:
```
[
    {
        "id": 1,
        "title": "Marketing"
    },
    {
        "id": 2,
        "title": "Rh"
    },
    {
        "id": 3,
        "title": "CX"
    },
    {
        "id": 4,
        "title": "CEO"
    },
    {
        "id": 5,
        "title": "Comer"
    }
]
```

2024-11-23 21:43 UTC, paulo-granthon requested changes

2024-11-23 21:43 UTC, paulo-granthon commented on src/service/service_group_access.go
> +	}
um departamento da lista `DepartmentIDs` pode não existir e a query não resultará em erro

pra saber de fato se todos os departamentos existem, precisaria ver se `departments` possui `len(DepartmentIDs)` items (se o tamanho da lista `DepartmentIDs` é igual ao tamanho da lista `departments`);

2024-11-23 21:43 UTC, paulo-granthon commented on src/server/hiring_process.go
> +// @Router /departments [get]
```suggestion
// @Router /suggestions/departments [get]
```

2024-11-23 21:43 UTC, paulo-granthon commented on src/server/hiring_process.go
> +// @Router /group_acess [post]
essa rota do swagger não condiz com a rota que está sendo criada, o certo seria:

```suggestion
// @Router /groupAccess/groupAccess [post]
```

ou melhor ainda, deixando padronizado (da forma que estão todos os outros endpoints) na questão de camel case vs pascal case:

```suggestion
// @Router /group_access/group_access [post]
```

melhor ainda, reduzindo repetição:

```suggestion
// @Router /group_access [post]
```
<br>

> [!NOTE]
segunda e terceira sugestão envolvem trocar na linha 42 tbm

> [!NOTE]
no caso da terceira sugestão, na linha 42 ficaria `groupAccess.POST("", CreateGroupAcess(dbClient))` (string vazia como `path`)

2024-11-23 21:43 UTC, paulo-granthon commented on src/server/hiring_process.go
> +}
retorno da rota não condiz com o que está documentado no swagger, aparentemente está retornando o resultado da query do `ent` diretamente sem tratamento (contendo inclusive o campo `edges`):

<details><summary>imagem</summary>
<img src="https://github.com/user-attachments/assets/de229d4f-0cae-465a-abbc-4e0f1915b0da">
</details>

2024-11-23 21:43 UTC, paulo-granthon commented on src/server/hiring_process.go
> +// @Router /group_acess [get]
essa rota do swagger não condiz com a rota que está sendo criada, o certo seria:

```suggestion
// @Router /group_access/List [get]
```

ou, também padronizando para snake_case:

```suggestion
// @Router /group_access/list [get]
```

ou, tirando a necessidade do subpath `list`:

```suggestion
// @Router /group_access [get]
```

> [!NOTE]
segunda e terceira sugestão envolvem trocar na linha 41 tbm

> [!NOTE]
no caso da terceira sugestão, na linha 41 ficaria `groupAccess.GET("", ListGroupAcess(dbClient))` (string vazia como `path`)

2024-11-23 21:43 UTC, paulo-granthon commented on src/service/service_group_access.go
> +		for _, dept := range group.Edges.Department {
considerar a possibilidade de erro ao tentar pegar os `Department` do `GroupAccess`:

```suggestion
		groupAccessDepartments, err := group.Edges.DepartmentOrErr()
		if err != nil {
		    return nil, fmt.Errorf("failed to retrieve `Department` of `GroupAccess: %w`, err)
		}
		
		for _, dept := range groupAccessDepartments {
```

2024-11-26 23:09 UTC, paulo-granthon approved these changes

2024-11-27 00:25 UTC, markusgomes approved these changes

2024-11-28 23:25 UTC, merged